name: Richard Searle
highlighter: rouge
redcarpet:
  extensions: ["jekyll-gist", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
description:  Richard Searle's Blog
url:          http://searler.github.io/
gems:
  - jekyll-gist
